_type_: maniskill_env
config:
  env_name: AssemblingKits-v1
  robot_uids: "xarm6_robotiq"
  control_mode: "pd_joint_delta_pos"

  root_pose:
    p: [-0.35, 0.2, -0.8]
    q: [1, 0, 0, 0] #[0.707, 0, 0, 0.707]

  goal_site:
    p: [-0.15, 0.3, 0.3]

  auto_record_success: true
  auto_record_success_threshold: 40
