ik_solver: ./ik_right.yaml

viewer: "vr_gripper"
tele:
  order: [right] 
  gripper_action_joint_names: [[left_outer_knuckle_joint]]

  reset_state: true

  config:
    _type_: "vr_gripper"
    config:
      reverse_gripper: true
      trigger_limit: [[0., 0.8]]
      trigger_scale: 3
