robot:
  urdf: ${oc.env:MANISKILL_ASSETS}/robots/panda/panda_v2.urdf
  fix_root_link: false
  cut:
    root: panda_hand
    cuts: [panda_hand_tcp, panda_leftfinger, panda_rightfinger]
  qpos: [0.0, 0.392, 0, -1.96, 0, 2.36, 0.785]


ik:
  ee_pose_convertor: [q: [0, 1, 0, 0]]
  ee_name: ["panda_hand"]
  fix_joint_indices: []
  n_retry: 0
  max_iterations: 100
  threshold: 1e-3
  use_projected_ik: false # true
  mod_2pi: false # true
